# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\admin\Nutstore\1\2022\Project\BrainICROA\src\Arm3DPosWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Arm3DPostionWidget(object):
    def setupUi(self, Arm3DPostionWidget):
        Arm3DPostionWidget.setObjectName("Arm3DPostionWidget")
        Arm3DPostionWidget.resize(614, 475)
        self.gridLayout = QtWidgets.QGridLayout(Arm3DPostionWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3d = QtWidgets.QGridLayout()
        self.gridLayout_3d.setObjectName("gridLayout_3d")
        self.gridLayout.addLayout(self.gridLayout_3d, 0, 0, 1, 1)
        self.pb_close = QtWidgets.QPushButton(Arm3DPostionWidget)
        self.pb_close.setObjectName("pb_close")
        self.gridLayout.addWidget(self.pb_close, 1, 0, 1, 1)

        self.retranslateUi(Arm3DPostionWidget)
        QtCore.QMetaObject.connectSlotsByName(Arm3DPostionWidget)

    def retranslateUi(self, Arm3DPostionWidget):
        _translate = QtCore.QCoreApplication.translate
        Arm3DPostionWidget.setWindowTitle(_translate("Arm3DPostionWidget", "Arm Position Widget"))
        self.pb_close.setText(_translate("Arm3DPostionWidget", "Close"))
