# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\admin\Nutstore\1\2022\Project\BrainICROA\src\GraspDistanceDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraspDistanceDialog(object):
    def setupUi(self, GraspDistanceDialog):
        GraspDistanceDialog.setObjectName("GraspDistanceDialog")
        GraspDistanceDialog.resize(613, 479)
        self.gridLayout = QtWidgets.QGridLayout(GraspDistanceDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView_distance = PlotWidget(GraspDistanceDialog)
        self.graphicsView_distance.setObjectName("graphicsView_distance")
        self.gridLayout.addWidget(self.graphicsView_distance, 0, 0, 1, 1)
        self.pb_close = QtWidgets.QPushButton(GraspDistanceDialog)
        self.pb_close.setObjectName("pb_close")
        self.gridLayout.addWidget(self.pb_close, 1, 0, 1, 1)

        self.retranslateUi(GraspDistanceDialog)
        QtCore.QMetaObject.connectSlotsByName(GraspDistanceDialog)

    def retranslateUi(self, GraspDistanceDialog):
        _translate = QtCore.QCoreApplication.translate
        GraspDistanceDialog.setWindowTitle(_translate("GraspDistanceDialog", "Dialog"))
        self.pb_close.setText(_translate("GraspDistanceDialog", "Close"))
from pyqtgraph import PlotWidget
