# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\admin\Nutstore\1\2022\Project\BrainICROA\src\ImageWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageWidget(object):
    def setupUi(self, ImageWidget):
        ImageWidget.setObjectName("ImageWidget")
        ImageWidget.resize(1400, 900)
        ImageWidget.setMinimumSize(QtCore.QSize(1400, 900))
        ImageWidget.setStyleSheet("border-color: rgb(0, 0, 0);")

        self.retranslateUi(ImageWidget)
        QtCore.QMetaObject.connectSlotsByName(ImageWidget)

    def retranslateUi(self, ImageWidget):
        _translate = QtCore.QCoreApplication.translate
        ImageWidget.setWindowTitle(_translate("ImageWidget", "Form"))
