# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\admin\Nutstore\1\2022\Project\BrainICROA\src\StiSpikeSignalDataDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StiSpikeSignalDataDialog(object):
    def setupUi(self, StiSpikeSignalDataDialog):
        StiSpikeSignalDataDialog.setObjectName("StiSpikeSignalDataDialog")
        StiSpikeSignalDataDialog.resize(559, 664)
        self.gridLayout = QtWidgets.QGridLayout(StiSpikeSignalDataDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView_left_sti = PlotWidget(StiSpikeSignalDataDialog)
        self.graphicsView_left_sti.setObjectName("graphicsView_left_sti")
        self.gridLayout.addWidget(self.graphicsView_left_sti, 0, 0, 1, 1)
        self.graphicsView_right_sti = PlotWidget(StiSpikeSignalDataDialog)
        self.graphicsView_right_sti.setObjectName("graphicsView_right_sti")
        self.gridLayout.addWidget(self.graphicsView_right_sti, 1, 0, 1, 1)
        self.graphicsView_sti_difference = PlotWidget(StiSpikeSignalDataDialog)
        self.graphicsView_sti_difference.setObjectName("graphicsView_sti_difference")
        self.gridLayout.addWidget(self.graphicsView_sti_difference, 2, 0, 1, 1)
        self.graphicsView_left_spikes = PlotWidget(StiSpikeSignalDataDialog)
        self.graphicsView_left_spikes.setObjectName("graphicsView_left_spikes")
        self.gridLayout.addWidget(self.graphicsView_left_spikes, 3, 0, 1, 1)
        self.graphicsView_right_spikes = PlotWidget(StiSpikeSignalDataDialog)
        self.graphicsView_right_spikes.setObjectName("graphicsView_right_spikes")
        self.gridLayout.addWidget(self.graphicsView_right_spikes, 4, 0, 1, 1)
        self.graphicsView_spikes_difference = PlotWidget(StiSpikeSignalDataDialog)
        self.graphicsView_spikes_difference.setObjectName("graphicsView_spikes_difference")
        self.gridLayout.addWidget(self.graphicsView_spikes_difference, 5, 0, 1, 1)
        self.pb_close = QtWidgets.QPushButton(StiSpikeSignalDataDialog)
        self.pb_close.setObjectName("pb_close")
        self.gridLayout.addWidget(self.pb_close, 6, 0, 1, 1)

        self.retranslateUi(StiSpikeSignalDataDialog)
        QtCore.QMetaObject.connectSlotsByName(StiSpikeSignalDataDialog)

    def retranslateUi(self, StiSpikeSignalDataDialog):
        _translate = QtCore.QCoreApplication.translate
        StiSpikeSignalDataDialog.setWindowTitle(_translate("StiSpikeSignalDataDialog", "Dialog"))
        self.pb_close.setText(_translate("StiSpikeSignalDataDialog", "Close"))
from pyqtgraph import PlotWidget
